# Generated by Django 3.1.5 on 2021-02-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comrades', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='holiday_type',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidays',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_holidays', to='comrades.country'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
