# Generated by Django 3.1.5 on 2021-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210204_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='holiday_type',
        ),
        migrations.AddField(
            model_name='holidays',
            name='duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
