# Generated by Django 3.1.5 on 2021-02-07 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210204_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='remind',
            field=models.CharField(choices=[('', 'do not remind'), (datetime.timedelta(seconds=3600), 'remind me in an hour'), (datetime.timedelta(seconds=7200), 'remind me in two hours'), (datetime.timedelta(seconds=14400), 'remind me in four hours'), (datetime.timedelta(days=1), 'remind me of the day'), (datetime.timedelta(days=7), 'remind me a week in advance')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='time_to_remind',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.TimeField(blank=True, default='23:59'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
