# Generated by Django 3.1.5 on 2021-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210207_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
