# Generated by Django 3.1.5 on 2021-02-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comrades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_name',
        ),
    ]
