# Generated by Django 3.1.5 on 2021-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comrades', '0002_auto_20210131_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
