# Generated by Django 3.1.5 on 2021-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comrades', '0003_auto_20210211_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
