# Generated by Django 3.1.5 on 2021-02-15 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comrades', '0004_country_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='offset',
            field=models.CharField(choices=[('', 'Greenwich Mean time'), (datetime.timedelta(seconds=10800), '3 hours')], default='', max_length=30),
        ),
    ]
